---
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
mode: script
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.24.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.netflix.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    fake-ip-filter:
    - "+.pool.ntp.org"
    - ntp7.*.com
    - ntp6.*.com
    - ntp5.*.com
    - ntp4.*.com
    - ntp3.*.com
    - ntp2.*.com
    - ntp1.*.com
    - ntp.*.com
    - time7.*.com
    - time6.*.com
    - time5.*.com
    - time4.*.com
    - time3.*.com
    - time2.*.com
    - time1.*.com
    - time.*.apple.com
    - time.*.edu.cn
    - time.*.gov
    - time.*.com
    - "*.home.arpa"
    - "*.local"
    - "*.test"
    - "*.localhost"
    - "*.invalid"
    - "*.example"
    - "*.localdomain"
    - time1.cloud.tencent.com
    - "*.ntp.org"
    - "*.time.edu"
    - "*.lan"
    - "*.ntp.org.cn"
    - "*.time.edu.cn"
    - "+.*"
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - dhcp://"eth0"
  - 192.168.8.1
  - 8.8.8.8
  - 8.8.4.4
  - https://dns.adguard.com/dns-query
  - https://dns.google/dns-query
  - tls://dns.google
  - tls://dns.adguard.com
  default-nameserver:
  - 74.82.42.42
  - 103.133.222.202
  - 8.8.8.8
  - 1.1.1.1
  - 192.168.8.1
  - 8.8.4.4
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - "+.google.com"
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - heartbeat.belkin.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - "+.dns.google"
proxy-providers:
  Booster1:
    type: file
    path: "./proxy_provider/simcard1.yaml"
    url: http://bit.ly/40PyUPL
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  Booster2:
    type: file
    path: "./proxy_provider/simcard2.yaml"
    url: http://bit.ly/3YOKmtk
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 99
proxy-groups:
- name: SIMASTER-V2.1
  type: select
  disable-udp: false
  proxies:
  - MANUAL
  - AUTO
  - FAILOVER
  - LOADBALANCE
  url: http://www.gstatic.com/generate_204
  interval: '99'
  interface-name: eth0
- name: MANUAL
  type: select
  disable-udp: false
  proxies:
  - MODEM1
  - MODEM2
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: AUTO
  type: url-test
  disable-udp: false
  proxies:
  - MODEM1
  - MODEM2
  url: http://www.gstatic.com/generate_204
  interval: '99'
  tolerance: '99'
- name: FAILOVER
  type: fallback
  disable-udp: false
  proxies:
  - MODEM1
  - MODEM2
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: LOADBALANCE
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - MODEM1
  - MODEM2
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: MODEM1
  type: select
  disable-udp: false
  proxies:
  - M1-MANUAL
  - M1-AUTO
  - M1-FAILOVER
  - M1-LOADBALANCE
  url: http://www.gstatic.com/generate_204
  interval: '99'
  interface-name: eth0
- name: MODEM2
  type: select
  disable-udp: false
  proxies:
  - M2-MANUAL
  - M2-AUTO
  - M2-FAILOVER
  - M2-LOADBALANCE
  url: http://www.gstatic.com/generate_204
  interval: '99'
  interface-name: eth0
- name: M1-MANUAL
  type: select
  disable-udp: false
  use:
  - Booster1
  url: http://www.gstatic.com/generate_204
  interval: '99'
  tolerance: '99'
- name: M2-MANUAL
  type: select
  disable-udp: false
  use:
  - Booster2
  url: http://www.gstatic.com/generate_204
  interval: '99'
  tolerance: '99'
- name: M1-AUTO
  type: url-test
  disable-udp: false
  use:
  - Booster1
  url: http://www.gstatic.com/generate_204
  interval: '99'
  tolerance: '99'
- name: M2-AUTO
  type: url-test
  disable-udp: false
  use:
  - Booster2
  url: http://www.gstatic.com/generate_204
  interval: '99'
  tolerance: '99'
- name: M1-FAILOVER
  type: fallback
  disable-udp: false
  use:
  - Booster1
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: M2-FAILOVER
  type: fallback
  disable-udp: false
  use:
  - Booster2
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: M1-LOADBALANCE
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Booster1
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: M2-LOADBALANCE
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Booster2
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: GAMING
  type: select
  disable-udp: false
  proxies:
  - M1-MANUAL
  - M1-AUTO
  - M1-FAILOVER
  - M1-LOADBALANCE
  - M2-MANUAL
  - M2-AUTO
  - M2-FAILOVER
  - M2-LOADBALANCE
  - DIRECT
  interface-name: eth0
- name: SOSMED
  type: select
  disable-udp: false
  proxies:
  - M1-MANUAL
  - M1-AUTO
  - M1-FAILOVER
  - M1-LOADBALANCE
  - M2-MANUAL
  - M2-AUTO
  - M2-FAILOVER
  - M2-LOADBALANCE
  - DIRECT
  interface-name: eth0 
- name: STREAMING
  type: select
  disable-udp: false
  proxies:
  - M1-MANUAL
  - M1-AUTO
  - M1-FAILOVER
  - M1-LOADBALANCE
  - M2-MANUAL
  - M2-AUTO
  - M2-FAILOVER
  - M2-LOADBALANCE
  - DIRECT
  interface-name: eth0
- name: OLSHOP
  type: select
  disable-udp: false
  proxies:
  - M1-MANUAL
  - M1-AUTO
  - M1-FAILOVER
  - M1-LOADBALANCE
  - M2-MANUAL
  - M2-AUTO
  - M2-FAILOVER
  - M2-LOADBALANCE
  - DIRECT
  interface-name: eth0
- name: BANK
  type: select
  disable-udp: false
  proxies:
  - M1-MANUAL
  - M1-AUTO
  - M1-FAILOVER
  - M1-LOADBALANCE
  - M2-MANUAL
  - M2-AUTO
  - M2-FAILOVER
  - M2-LOADBALANCE
  - DIRECT
  interface-name: eth0
- name: CHATTING
  type: select
  disable-udp: false
  proxies:
  - M1-MANUAL
  - M1-AUTO
  - M1-FAILOVER
  - M1-LOADBALANCE
  - M2-MANUAL
  - M2-AUTO
  - M2-FAILOVER
  - M2-LOADBALANCE
  - DIRECT
  interface-name: eth0
- name: KRYPTO
  type: select
  disable-udp: false
  proxies:
  - M1-MANUAL
  - M1-AUTO
  - M1-FAILOVER
  - M1-LOADBALANCE
  - M2-MANUAL
  - M2-AUTO
  - M2-FAILOVER
  - M2-LOADBALANCE
  interface-name: eth0
rule-providers:
  Boost-Game:
    type: http
    behavior: domain
    path: "./rule_provider/rule-game.yaml"
    url: http://bit.ly/3YQyCXb
    interval: 3600
  Boost-Sosmed:
    type: http
    behavior: domain
    path: "./rule_provider/rule-sosmed.yaml"
    url: http://bit.ly/3S3kO9t
    interval: 3600
  Boost-Stream:
    type: http
    behavior: domain
    path: "./rule_provider/rule-stream.yaml"
    url: http://bit.ly/3xm7hR0
    interval: 3600
  Boost-Olshop:
    type: http
    behavior: domain
    path: "./rule_provider/rule-olshop.yaml"
    url: http://bit.ly/3YvE41O
    interval: 3600
  Boost-Bank:
    type: http
    behavior: domain
    path: "./rule_provider/rule-bank.yaml"
    url: http://bit.ly/3lzi8nH
    interval: 3600
  Boost-Chatting:
    type: http
    behavior: domain
    path: "./rule_provider/rule-chatting.yaml"
    url: http://bit.ly/3YEHJKA
    interval: 3600
  Boost-Krypto:
    type: http
    behavior: domain
    path: "./rule_provider/rule-krypto.yaml"
    url: http://bit.ly/3RXxaQg
    interval: 3600
script:
  code: |
    def main(ctx, metadata):
        ruleset_action = {"Boost-Game": "GAMING,",
            "Boost-Sosmed": "SOSMED",
            "Boost-Stream": "STREAMING",
            "Boost-Olshop": "OLSHOP",
            "Boost-Bank": "BANK",
            "Boost-Chatting": "CHATTING",
            "Boost-Krypto": "KRYPTO",
          }

        port = int(metadata["dst_port"])

        if metadata["network"] == "UDP":
            if port == "21,22,23,53,80,443,8443,9993":
                ctx.log('[Script] matched QUIC traffic use SIMASTER-V2.1')
                return "SIMASTER-V2.1"

        if metadata["dst_ip"] == "":
            metadata["dst_ip"] = ctx.resolve_ip(metadata["host"])

        port_list = [21, 22, 23, 53, 80, 81, 123, 443, 853, 5353, 8000, 8008, 8080, 8081, 8090, 8443, 8888, 9993]
        if port not in port_list:
            ctx.log('[Script] not common port use SIMASTER-V2.1')
            return "SIMASTER-V2.1"

        if metadata["dst_ip"] == "":
            return "DIRECT"

        for ruleset in ruleset_action:
            if ctx.rule_providers[ruleset].match(metadata):
                return ruleset_action[ruleset]

        code = ctx.geoip(metadata["dst_ip"])
        if code == "ID":
            ctx.log('[Script] Geoip ID')
            return "SIMASTER-V2.1"

        ctx.log('[Script] SIMASTER')
        return "SIMASTER-V2.1"
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Boost-Game,GAMING
- RULE-SET,Boost-Sosmed,SOSMED
- RULE-SET,Boost-Stream,STREAMING
- RULE-SET,Boost-Olshop,OLSHOP
- RULE-SET,Boost-Bank,BANK
- RULE-SET,Boost-Chatting,CHATTING
- RULE-SET,Boost-Krypto,KRYPTO
- GEOIP,ID,SIMASTER-V2.1
- MATCH,SIMASTER-V2.1
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
secret: mwns
bind-address: "*"
experimental:
  sniff-tls-sni: true
authentication:
- Clash:v3XccHcM
